"""add schedule mode

迁移 ID: 2c81885ebe94
父迁移: 9af63132d74a
创建时间: 2026-05-24 13:30:01.043548

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


revision: str = "2c81885ebe94"
down_revision: str | Sequence[str] | None = "9af63132d74a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_wordcloud_schedule", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "schedule_mode",
                sa.Enum(
                    "完整周期",
                    "周期末",
                    name="schedulemode",
                    native_enum=False,
                ),
                server_default="完整周期",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_wordcloud_schedule", schema=None
    ) as batch_op:
        batch_op.drop_column("schedule_mode")

    # ### end Alembic commands ###
