"""migrate target

迁移 ID: 4f1a6b35e888
父迁移: e594c73f4e1d
创建时间: 2025-08-12 12:48:46.578366

"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from alembic import op
from nonebot import logger
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "4f1a6b35e888"
down_revision: str | Sequence[str] | None = "e594c73f4e1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    Base = automap_base()
    Base.prepare(op.get_bind())
    Schedule = Base.classes.nonebot_plugin_wordcloud_schedule

    session = Session(op.get_bind())
    schedules = session.query(Schedule).all()
    logger.info(f"wordcloud: 发现 {len(schedules)} 个定时发送计划，正在迁移...")
    for schedule in schedules:
        logger.debug(
            f"wordcloud: 正在迁移定时发送计划 {schedule.time} {schedule.target}"
        )
        target = json.loads(schedule.target)
        if target.platform_type == "QQ Group":
            pass
        else:
            logger.warning(
                f"wordcloud: 不支持的目标平台类型 {target.platform_type}，已跳过"
            )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
