"""remove target

迁移 ID: 80857cd51ec7
父迁移: 4f1a6b35e888
创建时间: 2025-08-12 12:49:27.277436

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "80857cd51ec7"
down_revision: str | Sequence[str] | None = "4f1a6b35e888"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_wordcloud_schedule", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "session_persist_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("target")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_wordcloud_schedule", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("target", sqlite.JSON(), nullable=False))
        batch_op.alter_column(
            "session_persist_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
