"""add schedule type

迁移 ID: 9af63132d74a
父迁移: 4f1a6b35e888
创建时间: 2026-05-24 13:01:24.267980

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "9af63132d74a"
down_revision: str | Sequence[str] | None = "4f1a6b35e888"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_wordcloud_schedule", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "schedule_type",
                sa.Enum(
                    "每日",
                    "每周",
                    "每月",
                    "每年",
                    name="scheduletype",
                    native_enum=False,
                ),
                server_default="每日",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_wordcloud_schedule", schema=None
    ) as batch_op:
        batch_op.drop_column("schedule_type")

    # ### end Alembic commands ###
